[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[functions.sendNotUpdatedSheets]
  schedule = "0 18 * * *" # every day at 6PM server time